[package]
name = "drill"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tera = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower-http = { version = "0.5", features = ["fs"] }
form_urlencoded = "1"
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio", "tls-rustls", "migrate", "uuid"] }
dotenvy = "0.15.7"
argon2 = "0.6.0"
uuid = "1.26.0"
axum-extra = { version = "0.9", features = ["cookie"] }
csv = "1.4.0"
